export const PREVENT_DOUBLE_CLICK_DELAY = 1000
export const BREAKPOINT = 1024

//date format
export const DATE_FORMAT = 'MM/DD/YYYY'
// CURRENT_BASE_OPERATION
export const CURRENT_BASE_OPERATION = 256

export const SSR_DEFAULT_SCREEN_SIZE_WIDTH = 1920
export const SSR_DEFAULT_SCREEN_SIZE_HEIGHT = 969
